"""Track data models

Revision ID: 47108532d657
Revises: 
Create Date: 2019-07-26 00:32:35.858674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47108532d657'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('track_segment',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.track_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('track_point',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('segment_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['segment_id'], ['track_segment.segment_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_index(op.f('ix_track_point_timestamp'), 'track_point', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_point_timestamp'), table_name='track_point')
    op.drop_table('track_point')
    op.drop_table('track_segment')
    op.drop_table('track')
    # ### end Alembic commands ###
