"""Moved track and track point to map blueprint

Revision ID: a2bc0f3ec32c
Revises: 
Create Date: 2019-08-12 20:01:47.110053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2bc0f3ec32c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('flash_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_type', sa.String(length=64), nullable=True),
    sa.Column('message', sa.String(length=256), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flash_message_message_type'), 'flash_message', ['message_type'], unique=False)
    op.create_index(op.f('ix_flash_message_timestamp'), 'flash_message', ['timestamp'], unique=False)
    op.create_table('task',
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index(op.f('ix_task_job_type'), 'task', ['job_type'], unique=False)
    op.create_table('track',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('track_point',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_index(op.f('ix_track_point_timestamp'), 'track_point', ['timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_point_timestamp'), table_name='track_point')
    op.drop_table('track_point')
    op.drop_table('track')
    op.drop_index(op.f('ix_task_job_type'), table_name='task')
    op.drop_table('task')
    op.drop_index(op.f('ix_flash_message_timestamp'), table_name='flash_message')
    op.drop_index(op.f('ix_flash_message_message_type'), table_name='flash_message')
    op.drop_table('flash_message')
    # ### end Alembic commands ###
