"""Revised slimmer track info

Revision ID: b08659b95974
Revises: 
Create Date: 2019-07-28 00:38:37.427141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b08659b95974'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('track_point',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['track_id'], ['track.database_id'], ),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_index(op.f('ix_track_point_timestamp'), 'track_point', ['timestamp'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_track_point_timestamp'), table_name='track_point')
    op.drop_table('track_point')
    op.drop_table('track')
    # ### end Alembic commands ###
