"""Initial tables

Revision ID: c3c073500b93
Revises: 
Create Date: 2019-07-25 23:49:35.405148

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c073500b93'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('track',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('seg_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_table('track__point',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.Column('point_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('database_id')
    )
    op.create_index(op.f('ix_track__point_time'), 'track__point', ['time'], unique=False)
    op.create_table('track__segment',
    sa.Column('database_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('database_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('track__segment')
    op.drop_index(op.f('ix_track__point_time'), table_name='track__point')
    op.drop_table('track__point')
    op.drop_table('track')
    # ### end Alembic commands ###
