"""Added photo width and height

Revision ID: 39a3ae9a1016
Revises: 0a420bc5fb24
Create Date: 2019-08-28 23:31:05.404359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39a3ae9a1016'
down_revision = '0a420bc5fb24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('photo', sa.Column('width', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo', 'width')
    op.drop_column('photo', 'height')
    # ### end Alembic commands ###
