"""empty message

Revision ID: cf2d8ef33699
Revises: 39a3ae9a1016
Create Date: 2020-07-19 13:48:33.015392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf2d8ef33699'
down_revision = '39a3ae9a1016'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_task_job_type', table_name='task')
    op.drop_table('task')
    op.drop_index('ix_flash_message_message_type', table_name='flash_message')
    op.drop_index('ix_flash_message_timestamp', table_name='flash_message')
    op.drop_table('flash_message')
    op.add_column('track', sa.Column('filename', sa.String(length=60), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track', 'filename')
    op.create_table('flash_message',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message_type', sa.VARCHAR(length=64), nullable=True),
    sa.Column('message', sa.VARCHAR(length=256), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_flash_message_timestamp', 'flash_message', ['timestamp'], unique=False)
    op.create_index('ix_flash_message_message_type', 'flash_message', ['message_type'], unique=False)
    op.create_table('task',
    sa.Column('job_id', sa.VARCHAR(length=64), nullable=False),
    sa.Column('job_type', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_index('ix_task_job_type', 'task', ['job_type'], unique=False)
    # ### end Alembic commands ###
